# Generated by Django 5.2 on 2025-05-15 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role_course_lesson_hometask_hometasksubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
